name: alphalink_venv
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - pip:
      # ? NOTE: Changed scipy version
      # - scipy==1.7.1
      # - deepspeed==0.5.10
      - deepspeed
      - scipy==1.7.2

      - biopython==1.79
      - dm-tree==0.1.6
      - ml-collections==0.1.0
      - numpy==1.21.2
      - PyYAML==5.4.1
      - requests==2.26.0
      - tqdm==4.62.2
      - typing-extensions==3.10.0.2
      - pytorch_lightning==1.5.0
      - wandb==0.12.21
      - git+https://github.com/NVIDIA/dllogger.git
  
  # ? NOTE: PROBLEM IS HERE!
  - conda-forge::python=3.7
  # - conda-forge::setuptools=59.5.0
  - conda-forge::setuptools
  # - conda-forge::openmm=7.5.1
  - conda-forge::openmm

  - conda-forge::pip  
  - conda-forge::pdbfixer
  - conda-forge::cudatoolkit==11.3.*
  - bioconda::aria2
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pytorch::pytorch=1.12.*
  - matplotlib==3.5.3
